# Generated by Django 5.0.1 on 2024-01-13 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('note', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('FROM', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(default='', max_length=100)),
                ('complaint', models.CharField(default='', max_length=100)),
                ('reply', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(default='', max_length=100)),
                ('FROM', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phoneno', models.CharField(default='', max_length=100)),
                ('photo', models.CharField(default='', max_length=500)),
                ('course', models.CharField(default='', max_length=100)),
                ('institution', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(default='', max_length=100)),
                ('reply', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(default='', max_length=100)),
                ('NOTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.notes')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('photo', models.CharField(default='', max_length=500)),
                ('idproof', models.CharField(default='', max_length=500)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phoneno', models.CharField(default='', max_length=100)),
                ('houseno', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('PIN', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='TUTOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tutor'),
        ),
    ]
